import type { JifDataset } from "../../types/domain";
import { jifDatasetSchema } from "./schemas";

export const MAX_LOCAL_JIF_FILE_BYTES = 20 * 1024 * 1024;

export async function parseLocalJifFile(file: File): Promise<JifDataset> {
  if (!file.name.toLocaleLowerCase().endsWith(".json")) {
    throw new Error("Choose a JSON file generated by the JIF extraction script.");
  }
  if (file.size === 0) throw new Error("The selected JIF file is empty.");
  if (file.size > MAX_LOCAL_JIF_FILE_BYTES) {
    throw new Error("The selected JIF file exceeds the 20 MB local-import limit.");
  }

  let value: unknown;
  try {
    value = JSON.parse(await file.text());
  } catch {
    throw new Error("The selected file is not valid JSON.");
  }

  const parsed = jifDatasetSchema.safeParse(value);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    const location = issue?.path.length ? ` at ${issue.path.join(".")}` : "";
    throw new Error(`The JIF dataset does not match the required schema${location}.`);
  }
  return parsed.data;
}
